scheme:    
general:
    n: [50]
    dataset: ["Madissoon2019.h5ad","Krasnow2020.h5ad","Meyer5loc2021.h5ad"]
    data_path: ["/storage/groups/ml01/workspace/louis.kuemmerle/projects/G1/data/processed/"]
    process_adata: [["norm", "log1p"]]
    gene_subset: ["highly_variable"]
    penalty_keys: []
methods:
    spapros:
        specific:
            celltype_key: ["unified_celltypes"]
    pca:
        specific:
            variance_scaled: [False]
            absolute: [True]
            n_pcs: [20]
    DE:
        specific:
            obs_key: ["unified_celltypes"]
            rankby_abs: [False]    