data:
    name: "Madissoon"
    data_path: "/storage/groups/ml01/workspace/louis.kuemmerle/projects/G1/data/processed/"
    dataset: "Madissoon2019.h5ad"
    process_adata: ["norm", "log1p"]
    celltype_key: "original_celltype_ann"
    gene_subset: "highly_variable"
metrics:
    cluster_similarity:
        ns: [7,60]
        AUC_borders: [[7, 23], [24, 60]]
    knn_overlap:
        ks: [5, 10, 20, 30, 50]
    forest_clfs:
        ct_key: "original_celltype_ann"
        threshold: 0.8
    marker_corr:
        marker_list: "/home/icb/louis.kuemmerle/projects/st_probesets/data/marker_list/lung_marker_list.csv"
        per_celltype: True
        per_marker: True
        per_celltype_min_mean: 
        per_marker_min_mean: 0.025
    gene_corr:
        threshold: 0.8