scheme:    
general:
    n: [50]
    dataset: ["Madissoon2019.h5ad"]
    data_path: ["/storage/groups/ml01/workspace/louis.kuemmerle/projects/G1/data/processed/"]
    process_adata: [["norm", "log1p"]]
    gene_subset: ["highly_variable"]
    penalty_keys: []
methods:
    spapros:
        specific:
            celltype_key: ["original_celltype_ann"]
            pca_penalties: [["expression_penalty_lower","expression_penalty_upper"]]
            DE_penalties: [["expression_penalty_lower","expression_penalty_upper"]]
            m_penalties_adata_celltypes: [["expression_penalty_lower","expression_penalty_upper"]]
            m_penalties_list_celltypes: [["expression_penalty_upper"]]
        marker_list: ["/storage/groups/ml01/workspace/louis.kuemmerle/projects/G1/data/marker_list/reduced_lung_marker_list.csv"]