scheme:    
general:
    n: [50]
    dataset: ["Madissoon2019.h5ad"]
    data_path: ["/storage/groups/ml01/workspace/louis.kuemmerle/projects/G1/data/processed/"]
    process_adata: [["norm", "log1p"]]
    gene_subset: ["highly_variable"]
    penalty_keys: []
methods:
    spapros:
        specific:
            celltype_key: ["original_celltype_ann"]
    pca:
        general:
            process_adata: [["norm", "log1p"], ["norm", "log1p", "scale"]]
        specific:
            variance_scaled: [False]
            absolute: [True]
            n_pcs: [15, 20, 25]
            corr_penalty: []
    DE:
        specific:
            obs_key: ["original_celltype_ann"]
            rankby_abs: [False]
    random:
        scheme:
            n_seeds: 10
    highest_expr:
    hvg:             
    spca: 
        general:
            process_adata: [["norm", "log1p"], ["norm", "log1p", "scale"]]    
